-- 코드를 입력하세요
SELECT B.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.fv
FROM REST_INFO A,
(SELECT FOOD_TYPE, MAX(FAVORITES) as fv FROM REST_INFO GROUP BY FOOD_TYPE) B
WHERE B.fv = A.FAVORITES and B.FOOD_TYPE = A.FOOD_TYPE
ORDER BY A.FOOD_TYPE desc