-- 코드를 입력하세요
SELECT a.BOARD_ID, a.WRITER_ID, a.TITLE, a.PRICE, 
CASE
    WHEN a.STATUS = 'DONE' THEN '거래완료'
    WHEN a.STATUS = 'SALE' THEN '판매중'
    WHEN a.STATUS = 'RESERVED' THEN '예약중'
END
FROM USED_GOODS_BOARD a
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID desc