SELECT a.FLAVOR
FROM FIRST_HALF a
LEFT JOIN
(SELECT FLAVOR, SUM(TOTAL_ORDER) as tor FROM JULY GROUP BY flavor) b
on a.FLAVOR = b.FLAVOR
GROUP BY a.FLAVOR
ORDER BY SUM(a.TOTAL_ORDER + b.tor) desc
FETCH FIRST 3 row only