SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') as PUBLISHED_DATE 
FROM BOOK a
inner join AUTHOR b
on a.AUTHOR_ID = b.AUTHOR_ID
where a.CATEGORY LIKE '%경제%'
ORDER BY a.PUBLISHED_DATE asc;