-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES,
a.ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) as 'SCORE'
FROM REST_INFO a
inner join REST_REVIEW b
on a.REST_ID = b.REST_ID
WHERE a.ADDRESS LIKE '서울%'
GROUP BY a.REST_NAME, a.ADDRESS
ORDER BY SCORE desc, a.FAVORITES desc